name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the client image (Dev)
      run: docker build ./client -f ./client/Dockerfile.dev -t mahmoudzidan/react-test

    - name: Test the image
      run: docker run -e CI=true mahmoudzidan/react-test npm run test -- --coverage

    - name: Build the client image
      run: docker build ./client -t mahmoudzidan/multi-client

    - name: Build the ngix image
      run: docker build ./ngix -t mahmoudzidan/multi-ngix

    - name: Build the server image
      run: docker build ./server -t mahmoudzidan/multi-server

    - name: Build the worker image
      run: docker build ./worker -t mahmoudzidan/multi-worker

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSOWRD }}
