name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build ./client -f ./client/Dockerfile.dev -t mahmoudzidan/react-test

    - name: Test the image
      run: docker run -e CI=true mahmoudzidan/react-test npm run test -- --coverage
