name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the client image (Dev)
      run: docker build ./client -f ./client/Dockerfile.dev -t mahmoudzidan/react-test

    - name: Test the image
      run: docker run -e CI=true mahmoudzidan/react-test npm run test -- --coverage


  Push to DockerHub:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the client image
      run: docker build ./client -t mahmoudzidan/multi-client

    - name: Build the nginx image
      run: docker build ./nginx -t mahmoudzidan/multi-nginx

    - name: Build the server image
      run: docker build ./server -t mahmoudzidan/multi-server

    - name: Build the worker image
      run: docker build ./worker -t mahmoudzidan/multi-worker

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push images to Docker Hub
      run: |
        docker push mahmoudzidan/multi-client
        docker push mahmoudzidan/multi-nginx
        docker push mahmoudzidan/multi-server
        docker push mahmoudzidan/multi-worker
